apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-page #Name of deployment
spec:
  replicas: 2 # Instances of our pod. kubectl get all
  selector:
    matchLabels:
      app:  demo-web-page
  template:
    metadata:
      labels:
        app: demo-web-page
    spec:
      containers:
      - name: index-web-container01
        image: vibhordubey/html-webapp:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always
