apiVersion: v1
kind: Service
metadata:
  name: html-webapp
  labels:
    app: demo-web-page
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 32765
 selector:
    app: demo-web-page

