apiVersion: apps/v1
kind: Deployment
metadata:
 name: example-deploy
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: example
 template:
   metadata:
     labels:
       app: example
   spec:
     containers:
     - name: example
       image: example:v0
       imagePullPolicy: Never
       ports:
       - containerPort: 8000
       livenessProbe: # Important Section
         grpc:
           port: 8000
         initialDelaySeconds: 5
         periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
 name: example-service
spec:
 # type: NodePort
 selector:
   app: example
 ports:
   - protocol: TCP
     port: 8000