apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-deployment
    namespace: k8s
    labels:
      app: mongodb
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongodb
    template:
      metadata:
        labels:
          app: mongodb
      spec:
          containers:
          - name: mongodb
            image: mongo:2.4.11 # Using old image as latest image was causing issue.
            ports:
              - containerPort: 27017
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret #mongodb-secret yaml name.
                    key: mongo-root-username # Defined in mongodb-secret.
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: k8s
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # Service Port
      targetPort: 27017 #Container Port

