apiVersion: v1
kind: Pod
metadata:
  name: http-get-pod
spec:
  containers:
  - name: http-get-container
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20

# In this example:

#     The Pod named "http-get-pod" runs an Nginx container.
#     A liveness probe is defined for the container, which performs an HTTP GET request to the root path ("/") of the container's port 80.
#     The initialDelaySeconds field specifies how long Kubernetes should wait before performing the first probe.
#     The periodSeconds field specifies the interval at which the probe should be performed.

# This setup ensures that Kubernetes checks the health of the Pod by sending an HTTP GET request to it at regular intervals, starting after an initial delay. If the probe fails, Kubernetes can take action such as restarting the Pod.


#Output:
# Events:
#   Type     Reason     Age   From               Message
#   ----     ------     ----  ----               -------
#   Normal   Scheduled  38s   default-scheduler  Successfully assigned default/http-get-pod-failure to minikube
#   Normal   Pulling    35s   kubelet            Pulling image "nginx"
#   Normal   Pulled     33s   kubelet            Successfully pulled image "nginx" in 2.616s (2.616s including waiting)
#   Normal   Created    32s   kubelet            Created container http-get-failure-container
#   Normal   Started    32s   kubelet            Started container http-get-failure-container
#   Warning  Unhealthy  17s   kubelet            Liveness probe failed: Get "http://10.244.0.12:90/": dial tcp 10.244.0.12:90: connect: connection refused