apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector: 
    app: story
  type: LoadBalancer # If we don't specify this then service will be exposed internally not outside of the cluster.
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000