apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: mycrds.vibhordubey333.com
spec:
    group: vibhordubey333.com
    versions:
      - name: v1
        served : true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      replicas:
                        type: integer
                      image:
                        type: string
    scope: Namespaced
    names:
      plural: mycrds
      singular: mycrd
      kind: GoApp
      shortNames:
        - myc