apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production # Changed to match template labels
  replicas: 3
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
